# main.spec
# -*- mode: python -*-
block_cipher = None

a = Analysis(['main.py'],
             pathex=['.'],
             binaries=[],
             datas=[
                ('temp_my_app/repository/metadata/root.json', '.'),
                 ('work_py', 'work_py'),
                 ('users', 'users'),
                 ('tests', 'tests'),
                 ('log_files', 'log_files'),
                 ('property_excel', 'property_excel'),
                 ('imageFiles', 'imageFiles'),
                 ('gnkt_data', 'gnkt_data'),
                 ('data_base', 'data_base'),
                 ('podpisant.json', '.'),
                 ('work_json.py', '.'),
                 ('data_list.py', '.'),
                 ('requirements.txt', '.'),
                 ('plan.py', '.'),
                 ('key.key', '.'),
                 ('decrypt.py', '.'),
                 ('perforation_correct_gnkt_frez.py', '.'),
                 ('perforation_correct.py', '.'),
                 ('open_pz.py', '.'),
                 ('krs.py', '.'),
                 ('H2S.py', '.'),
                 ('gnkt_opz.py', '.'),
                 ('gnkt_after_grp.py', '.'),
                 ('find.py', '.'),
                 ('data_correct_position_people.py', '.'),
                 ('data_correct.py', '.'),
                 ('cdng.py', '.'),
                 ('category_correct.py', '.'),
                 ('build_script.py', '.'),
                 ('block_name.py', '.'),
                 ('application_pvr.py', '.'),
                 ('application_gis.py', '.'),
                 ('.env', '.'),
             ],
             hiddenimports=[],
             hookspath=[],
             runtime_hooks=[],
             excludes=[],
             win_no_prefer_redirects=False,
             win_private_assemblies=False,
             cipher=block_cipher,
             noarchive=False)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)
exe = EXE(pyz,
           a.scripts,
           [],
           exclude_binaries=True,
           name='ZIMA',
           debug=False,
           bootloader_ignore_signals=False,
           strip=False,
           upx=True,
           console=True,
           icon='imageFiles/icon/zima_ico.ico')
coll = COLLECT(exe,
               a.binaries,
               a.zipfiles,
               a.datas,
               strip=False,
               upx=True,
               upx_exclude=[],
               name='ZIMA')
