name: Build PyInstaller
on:  ['push', 'pull_request']
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8' # Замените на нужную версию Python

      - name: Install PyInstaller
        run: pip install pyinstaller
#      - name: Install requirements
#        run: pip install -r requirements.txt
      - name: Build executable
        run:
          pyinstaller --add-data data_base/data_base_well/database_well.py:data_base/data_base_well/database_well.py 
          --add-data data_base/data_base_well/databaseWell.db:data_base/data_base_well/databaseWell.db 
          --add-data data_base/work_with_base.py:data_base/work_with_base.py 
          --add-data data_base/database_without_juming.db:data_base/database_without_juming.db 
          --add-data gnkt_data/gnkt_data.py:gnkt_data/gnkt_data.py --add-data imageFiles:imageFiles 
          --add-data users/login_users.py:users/login_users.py --add-data work_py/acid_paker.py:work_py/acid_paker.py --add-data work_py/acids.py:work_py/acids.py --add-data work_py/advanted_file.py:work_py/advanted_file.py --add-data work_py/alone_oreration.py:work_py/alone_oreration.py --add-data work_py/calc_fond_nkt.py:work_py/calc_fond_nkt.py --add-data work_py/change_fluid.py:work_py/change_fluid.py --add-data work_py/claySolution.py:work_py/claySolution.py --add-data work_py/data_informations.py:work_py/data_informations.py --add-data work_py/descent_gno.py:work_py/descent_gno.py --add-data work_py/dop_plan_py.py:work_py/dop_plan_py.py --add-data work_py/drilling.py:work_py/drilling.py --add-data work_py/emergencyWork.py:work_py/emergencyWork.py --add-data work_py/geophysic.py:work_py/geophysic.py --add-data work_py/gnkt_frez.py:work_py/gnkt_frez.py --add-data work_py/gnkt_grp.py:work_py/gnkt_grp.py --add-data work_py/gpp.py:work_py/gpp.py --add-data work_py/grp.py:work_py/grp.py --add-data work_py/kompress.py:work_py/kompress.py --add-data work_py/leakage_column.py:work_py/leakage_column.py --add-data work_py/mkp.py:work_py/mkp.py --add-data work_py/mouse.py:work_py/mouse.py --add-data work_py/opressovka.py:work_py/opressovka.py --add-data work_py/perforation.py:work_py/perforation.py --add-data work_py/raiding.py:work_py/raiding.py --add-data work_py/rgdVcht.py:work_py/rgdVcht.py --add-data work_py/rir.py:work_py/rir.py --add-data work_py/sand_filling.py:work_py/sand_filling.py --add-data work_py/swabbing.py:work_py/swabbing.py --add-data work_py/template_without_skm.py:work_py/template_without_skm.py --add-data work_py/template_work.py:work_py/template_work.py --add-data work_py/vp_cm.py:work_py/vp_cm.py --add-data block_name.py:block_name.py --add-data category_correct.py:category_correct.py --add-data cdng.py:cdng.py --add-data data_correct.py:data_correct.py --add-data data_correct_position_people.py:data_correct_position_people.py --add-data find.py:find.py --add-data gnkt_after_grp.py:gnkt_after_grp.py --add-data gnkt_opz.py:gnkt_opz.py --add-data H2S.py:H2S.py --add-data krs.py:krs.py --add-data main.py:main.py --add-data open_pz.py:open_pz.py --add-data perforation_correct.py:perforation_correct.py --add-data perforation_correct_gnkt_frez.py:perforation_correct_gnkt_frez.py --add-data plan.py:plan.py --add-data plan23.py:plan23.py --add-data podpisant.json:podpisant.json --add-data proverka.py:proverka.py --add-data selectPlast.py:selectPlast.py --add-data well_data.py:well_data.py --add-data work_json.py:work_json.py --add-data application_gis.py:application_gis.py --add-data application_pvr.py:application_pvr.py main.py


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zima
          path: dist/main.exe
