name: Build PyInstaller
on:  ['push', 'pull_request']
jobs:
  build:
    runs-on: self-hosted windows-7
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # Замените на нужную версию Python
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Build executable
        run: pyinstaller --onefile main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: zima
          path: dist/zima.exe
