name: Build PyInstaller
on:  ['push', 'pull_request']
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install PyInstaller
        run: pip install pyinstaller pywin32
#      - name: Install requirements
#        run: pip install -r requirements.txt
      - name: Install dependencies
        run: pip install -r requirements.txt
#          - name: Build executable
#              run: pyinstaller --onefile --hidden-import data_base.data_base_well.database_well main.py
      - name: Build executable
        run:
          pyinstaller --noconfirm --onedir --icon=imageFiles/icon/zima_ico.ico --console --name "ZIMA"
          --add-data data_base:ZIMA/data_base
          
          --add-data work_py:ZIMA/work_py
          --add-data users:ZIMA/users
          --add-data property_excel:ZIMA/property_excel 
          --add-data imageFiles:ZIMA/imageFiles
          --add-data gnkt_data:ZIMA/
          --add-data data_base:ZIMA/ 
          --add-data work_json.py:ZIMA/.
          --add-data well_data.py:ZIMA/. 
          --add-data selectPlast.py:ZIMA/.
          --add-data proverka.py:ZIMA/ 
          --add-data plan23.py:ZIMA/ 
          --add-data plan.py:ZIMA/ 
          --add-data perforation_correct_gnkt_frez.py:ZIMA/
          --add-data perforation_correct.py:ZIMA/
          --add-data open_pz.py:ZIMA/
          --add-data krs.py:ZIMA/
          --add-data H2S.py:ZIMA/
          --add-data gnkt_opz.py:ZIMA/
          --add-data gnkt_after_grp.py:ZIMA/
          --add-data find.py:ZIMA/
          --add-data data_correct_position_people.py:ZIMA/
          --add-data data_correct.py:ZIMA/
          --add-data convert_xls.py:ZIMA/
          --add-data cdng.py:ZIMA/
          --add-data category_correct.py:ZIMA/
          --add-data build_script.py:ZIMA/
          --add-data block_name.py:ZIMA/
          --add-data application_pvr.py:ZIMA/
          --add-data application_gis.py:ZIMA/
          --add-data data_base/users_database:ZIMA/
          --add-data gnkt_data:ZIMA/
          --add-data imageFiles:ZIMA/
          --add-data imageFiles/schema_well:ZIMA/
          --add-data imageFiles/pvo/oil:ZIMA/        
          main.py


      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ZIMA
          path: dist/*