name: Build PyInstaller

on:
  push:
    branches:
      - main
  pull_request:
      - main
  tags:
    - v[0-9]+.[0-9]+.[0-9]+*

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8' # Замените на нужную версию Python
      - name: Install PyInstaller
        run: pip install pyinstaller
      - name: Build executable
        run: pyinstaller --onefile main.py
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: zima
          path: dist/zima.exe
