name: Build PyInstaller
on:  ['push', 'pull_request']
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.8' # Замените на нужную версию Python

      - name: Install PyInstaller
        run: pip install pyinstaller
#      - name: Install requirements
#        run: pip install -r requirements.txt
      - name: Build executable
        run:
          pyinstaller 
          --add-data data_base:data_base
          --add-data D:\python\Create_work_krs\gnkt_data:gnkt_data
          --add-data D:\python\Create_work_krs\imageFiles:imageFiles
          --add-data D:\python\Create_work_krs\property_excel:property_excel
          --add-data D:\python\Create_work_krs\users:users
          --add-data D:\python\Create_work_krs\work_py:work_py
          --add-data D:\python\Create_work_krs\:block_name.py 
          --add-data D:\python\Create_work_krs\:category_correct.py 
          --add-data D:\python\Create_work_krs\cdng.py:cdng.py
          --add-data D:\python\Create_work_krs\data_correct.py:data_correct.py 
          --add-data D:\python\Create_work_krs\data_correct_position_people.py:data_correct_position_people.py 
          --add-data D:\python\Create_work_krs\find.py:find.py 
          --add-data D:\python\Create_work_krs\gnkt_after_grp.py:gnkt_after_grp.py 
          --add-data D:\python\Create_work_krs\gnkt_opz.py:gnkt_opz.py 
          --add-data D:\python\Create_work_krs\H2S.py:H2S.py 
          --add-data D:\python\Create_work_krs\krs.py:krs.py           
          --add-data D:\python\Create_work_krs\open_pz.py:open_pz.py 
          --add-data D:\python\Create_work_krs\perforation_correct.py:perforation_correct.py 
          --add-data D:\python\Create_work_krs\perforation_correct_gnkt_frez.py:perforation_correct_gnkt_frez.py 
          --add-data D:\python\Create_work_krs\plan.py:plan.py 
          --add-data D:\python\Create_work_krs\plan23.py:plan23.py 
          --add-data D:\python\Create_work_krs\podpisant.json:podpisant.json 
          --add-data D:\python\Create_work_krs\proverka.py:proverka.py 
          --add-data D:\python\Create_work_krs\selectPlast.py:selectPlast.py 
          --add-data D:\python\Create_work_krs\well_data.py:well_data.py 
          --add-data D:\python\Create_work_krs\work_json.py:work_json.py 
          --add-data D:\python\Create_work_krs\application_gis.py:application_gis.py 
          --add-data D:\python\Create_work_krs\application_pvr.py:application_pvr.py 
          main.py


      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zima
          path: dist/main.exe
